config/routes.rb
Rails.application.routes.draw do

  # VERB 'path', to: "controller#action", as: :prefix
  get '/', to: "flats#index", as: :flats

  # get '/flats/145'
  get '/flats/:id', to: "flats#show", as: :flat
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"


class FlatsController < ApplicationController
  before_action :set_flats

  def index
    # set_flats
  end

  def show
    # set_flats
    @flat = @flats.find { |flat| flat["id"] == params[:id].to_i}
    # @flat = Flat.find(params[:id])
  end

  def set_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>
<ul>
  <% @flats.each do |flat| %>
    <li class="flat">
      <%#= flat.name %>
      <%= link_to flat['name'], flat_path(flat["id"]) %> -  (<%= flat['price'] %><%= flat['priceCurrency'] %>)
      <p><%#= link_to "Learn More", flat_path(flat["id"]) %></p>
    </li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<h1><%= @flat["name"] %></h1>
<p><%= @flat["price"] %></p>
<%= link_to "Back", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>